- name: Setup Doxygen
  uses: marketplace/actions/setup-doxygen

- name: Generate Doxygen Documentation
  run: |
    doxygen doxygen/Doxyfile  # Adjust if your Doxyfile is elsewhere

- name: Configure Git
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
  
- name: Deploy to GitHub Pages
  run: |
    git fetch
    git checkout gh-pages || git checkout --orphan gh-pages
    git reset --hard
    rm -rf *  # Clear old documentation
    cp -r ${{ github.workspace }}/doxygen/html/* .  # Adjust this path as necessary
    git add .
    git commit -m "Update documentation" || echo "No changes to commit"
    git push origin gh-pages --force
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
