name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Doxygen
      uses: marketplace/actions/setup-doxygen

    - name: Generate Doxygen Documentation
      run: |
        cd doxygen
        doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: doxygen/html  # The folder the action should deploy.
        clean: true  # Automatically remove deleted files from the deployment
