name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on commits to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Documentation with Doxygen
        run: |
          cd doxygen
          doxygen Doxyfile

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .  # Clear current contents
          cp -r ../doxygen/html/* .  # Copy new docs
          git add .
          git commit -m "Deploy updated documentation" || echo "No changes to commit"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
