name: Deploy Documentation to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Documentation with Doxygen
        run: |
          cd doxygen
          doxygen Doxyfile
          cd ..

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .  # Clear current contents
          cp -r doxygen/html/* .  # Copy the new docs
          cp doxygen/new_index.html index.html
          git add .
          git commit -m "Deploy updated documentation" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ropg/OOKwiz.git gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
