name: Update GitHub Pages Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Doxygen
        uses: mattnotmitt/doxygen-action@v1

      - name: Generate Doxygen Documentation
        run: doxygen doxygen/Doxyfile

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
  
      - name: Deploy to GitHub Pages
        run: |
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          rm -rf *  # Clear old documentation
          cp -r ${{ github.workspace }}/doxygen/html/* .
          git add .
          git commit -m "Update documentation" || echo "No changes to commit"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
