name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on commits to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Documentation with Doxygen
      run: |
        cd doxygen
        doxygen Doxyfile

    - name: Deploy to GitHub Pages
      run: |
        git fetch
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        cp -r doxygen/html/* .
        git add .
        git commit -m "Deploy updated documentation" || echo "No changes to commit"
        git push origin gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
